version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: webapp
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - appdata:/data/db
    networks:
      - backend
  webserver:
    # image: razzocv/ap-webserver:latest
    depends_on:
      - mongodb
    build:
      context: webserver/
    command: /app/.venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 5000
    expose:
      - 5000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: "apiuser"
      MONGODB_PASSWORD: "apipassword"
    volumes:
      - appdatashare:/var/www/
    networks:
      - frontend
      - backend
  view:
    # image: razzocv/ap-webserver:latest
    depends_on:
      - webserver
    build:
      context: view/
    ports:
      - "3000:80"
    volumes:
      - ./view:/app
      - /app/node_modules
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: azure_file
    driver_opts:
      share_name: appdata
      storage_account_name: mongodbdataaccount
  appdata:
    driver: azure_file
    driver_opts:
      share_name: appdatashare
      storage_account_name: appdataaccount


