version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - database.dev
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"

  webserver:
    depends_on:
      - postgres
    build:
      context: webserver/
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www/
    networks:
      - backend
      - frontend

  view:
    depends_on:
      - webserver
    build:
      context: view/
    ports:
      - "3000:80"
    volumes:
      - ./view:/app
      - /app/node_modules
    networks:
      - frontend

  analysis:
    depends_on:
      - webserver
    build:
      context: analysis/
    ports:
      - "5001:5001"
    volumes:
      - nltkdata:/root/nltk_data
    networks:
      - backend

  fetcher:
    depends_on:
      - webserver
    build:
      context: fetcher/
    ports:
      - "5002:5002"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
  appdata:
    driver: local
  nltkdata:
    driver: local
