openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/users/{user_id}:
    get:
      tags:
        - users
      summary: Retrive the whole data of a specific user
      operationId: get_users_user_id_api_users__user_id__get
      parameters:
        - required: true
          schema:
            title: User Id
            type: integer
          name: user_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
    delete:
      tags:
        - users
      summary: Delete the whole data of a specific user
      operationId: delete_users_user_id_api_users__user_id__delete
      parameters:
        - required: true
          schema:
            title: User Id
            type: integer
          name: user_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/users/{user_id}/rss-feeds:
    put:
      tags:
        - users
      summary: Overwrite the whole rss-feed data associated to a specific user
      operationId: put_users_rss_feed_api_users__user_id__rss_feeds_put
      parameters:
        - required: true
          schema:
            title: User Id
            type: integer
          name: user_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRssFeedsDto'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/news:
    get:
      tags:
        - news
      summary: Retrive content of the specified RSS feed, exploiting fetcher module
      operationId: call_fetcher_api_news_get
      parameters:
        - required: true
          schema:
            title: Feed Url
            type: string
          name: feed_url
          in: query
        - required: true
          schema:
            title: Limit
            type: integer
          name: limit
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/news/articles:
    get:
      tags:
        - news
      summary: Retrive the full text of the specific article, exploiting the newspaper module
      operationId: call_newspaper_api_news_articles_get
      parameters:
        - required: true
          schema:
            title: Article Url
            type: string
          name: article_url
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/news/articles/summary:
    post:
      tags:
        - news
      summary: Retrive the summary of the specific article, exploiting the analysis module
      operationId: call_summary_api_news_articles_summary_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsText'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    NewsText:
      title: NewsText
      type: object
      properties:
        body:
          title: Body
          type: string
          default: A very long text, mainly written in English
    RssFeedDto:
      title: RssFeedDto
      type: object
      properties:
        url:
          title: Url
          type: string
          default: http://feeds.bbci.co.uk/news/world/rss.xml
        rank:
          title: Rank
          type: integer
          default: 1
    UserRssFeedsDto:
      title: UserRssFeedsDto
      required:
        - rssFeeds
      type: object
      properties:
        user_id:
          title: User Id
          type: integer
          default: 1
        rssFeeds:
          title: Rssfeeds
          type: array
          items:
            $ref: '#/components/schemas/RssFeedDto'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /auth/token
tags:
  - name: news
    description: Operations for managing news from RSS feeds
  - name: users
    description: Operations for managing users of the system
