name: Build Docker Image for Newspaper

on:
  push:
    branches:
      - "main"
    paths:
      - "newspaper/**"
      - ".github/workflows/newspaper-docker-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./newspaper
          file: ./newspaper/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ap-newspaper:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ap-newspaper:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ap-newspaper:buildcache,mode=max
