name: Docker Image CI for WebServer

on:
  push:
    branches:
      - "ci-test"
    paths:
      - "webserver/**"
      - ".github/workflows/webserver-docker-image.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./webserver/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ap-webserver:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ap-webserver:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ap-webserver:buildcache,mode=max
